// User types

export const USER_REGISTER_ERRORS = "USER_REGISTER_ERRORS";
export const USER_LOGIN_ERRORS = "USER_LOGIN_ERRORS";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERRORS = "PROFILE_ERRORS";
export const TUTOR_SUCCESS = "TUTOR_SUCCESS";
export const TUTOR_ERRORS = "TUTOR_ERRORS";
export const GET_TUTOR_SUCCESS = "GET_TUTOR_SUCCESS";
export const GET_TUTOR_ERRORS = "GET_TUTOR_ERRORS";
